language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.2
    - android-22
    - android-24
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-22
    
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.gradle/caches/2.14.1
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper

before_script:
  - android list targets
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script: ./gradlew connectedAndroidTest

# DISABLED openjdk7 as it still gives me a buffer overflow fault.
# See issue https://github.com/ably/ably-java/issues/191
#  - openjdk7

# Buffer overflow patch. Source: https://github.com/travis-ci/travis-ci/issues/5227#issuecomment-165135711
#before_install:
#  - cat /etc/hosts # optionally check the content *before*
#  - sudo hostname "$(hostname | cut -c1-63)"
#  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts > /tmp/hosts
#  - sudo mv /tmp/hosts /etc/hosts
#  - cat /etc/hosts # optionally check the content *after*

#install: true
#script: "ret=0; ./gradlew java:testRealtimeSuite || ret=1; ./gradlew java:testRestSuite || ret=1; exit $ret"
