on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v2
         with:
           submodules: recursive
        run: ./gradlew checkstyleMain checkstyleTest checkWithCodenarc runUnitTests
