on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 24
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          script: ./gradlew :android:connectedAndroidTest

      - uses: actions/upload-artifact@v2
        with:
          name: android-build-reports
          path: android/build/reports/
