on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        android-api-level: [ 19, 24, 30 ]

    steps:
      - uses: actions/checkout@v2

      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.android-api-level }}
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew :android:connectedAndroidTest

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: android-build-reports
          path: android/build/reports/
