on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Run tests with gradle
        run: ./gradlew :java:testRestSuite :java:testRealtimeSuite

      - name: Upload results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: java-build-reports
          path: java/build/reports/
