on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: ./gradlew :java:testRestSuite :java:testRealtimeSuite

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: java-build-reports
          path: java/build/reports/
