on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      deployments: write
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::${{ secrets.ABLY_AWS_ACCOUNT_ID_SDK }}:role/ably-sdk-builds-ably-java
          role-session-name: "${{ github.run_id }}-${{ github.run_number }}"

      - name: Set up the JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build docs
        run: ./gradlew javadoc

      - name: Upload Documentation
        uses: ably/sdk-upload-action@v1
        with:
          sourcePath: java/build/docs/javadoc
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          artifactName: javadoc
